import { useState } from 'react'
import toast from 'react-hot-toast'
import { Coffee, FileText, Plus } from 'lucide-react'
import { useApp } from '../contexts/AppContext'
import Page from '../components/ui/Page'

export default function ReportsPage() { const { role } = useApp(); return <Page title={role === 'employee' ? 'Stok & modal harian' : 'Laporan operasional'} subtitle={role === 'employee' ? 'Lengkapi catatan operasional setelah absensi.' : 'Rekap performa Kantin Utama dalam satu tempat.'} action={role !== 'employee' && <button className="btn primary" onClick={() => window.print()}><FileText size={17} /> Export PDF</button>}>{role === 'employee' ? <DailyEntry /> : <ReportPreview />}</Page> }
function DailyEntry() { const [materials, setMaterials] = useState([{ name: '', amount: '' }]); const add = () => setMaterials((items) => [...items, { name: '', amount: '' }]); return <div className="form-panel"><div><span className="form-number">01</span><h2>Modal awal kas</h2><p>Catat nominal uang kas yang tersedia pagi ini.</p><label>Jumlah modal awal<input placeholder="Rp 0" inputMode="numeric" /></label></div><div><span className="form-number">02</span><h2>Stok bahan baku</h2><p>Tambahkan bahan yang digunakan hari ini.</p>{materials.map((material, index) => <div className="stock-line" key={index}><input placeholder="Nama bahan" value={material.name} onChange={(event) => setMaterials((items) => items.map((item, position) => position === index ? { ...item, name: event.target.value } : item))} /><input placeholder="Jumlah" value={material.amount} onChange={(event) => setMaterials((items) => items.map((item, position) => position === index ? { ...item, amount: event.target.value } : item))} /></div>)}<button className="btn outline small" onClick={add}><Plus size={15} /> Tambah bahan</button></div><button className="btn primary" onClick={() => toast.success('Catatan operasional disimpan.')}>Simpan catatan hari ini</button></div> }
function ReportPreview() { return <div className="report-preview"><div className="report-logo"><Coffee /> KantinKu <span>LAPORAN MINGGUAN</span></div><h2>Kantin Utama</h2><p>Periode 7–13 Juli 2026</p><div className="report-stats"><span><b>Rp 4.570.000</b>Total pendapatan</span><span><b>286</b>Pre-order</span><span><b>96%</b>Kehadiran</span></div><hr /><h3>Ringkasan pendapatan</h3><div className="report-line"><span>Cash</span><b>Rp 2.140.000</b></div><div className="report-line"><span>QRIS</span><b>Rp 1.980.000</b></div><div className="report-line"><span>Transfer</span><b>Rp 450.000</b></div></div> }
